In [1]:
import numpy
import pandas
import matplotlib.pyplot
z=(4,4)
a=numpy.ones(z)
print(a)
a*=5
print(a)
a= a.reshape((2, 8))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[[5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]]


In [2]:
import numpy
import pandas
import matplotlib.pyplot
df = pandas.DataFrame()
df.insert(0,'Число',(range(1,11)))
df.insert(1,'Квадрат',df['Число']*df['Число'])
df_2=df.loc[df['Число']%2==0]
df_2=df_2.drop(['Число'], axis='columns')

print(df_2)

   Квадрат
1        4
3       16
5       36
7       64
9      100
